'use client';
import {useEffect,useState} from 'react'; import {useRouter} from 'next/navigation'; import {postJSON,getJSON} from '../../lib/api';
const steps=['Product','Ingredients','Intended Use','Formulation','Business Goal','Assessment']; const ingSuggestions=['Ashwagandha','Tulsi','Giloy','Turmeric','Neem','Brahmi','Amla','Shatavari','Ginger','Triphala'];
const base={product_name:'',description:'',product_type:'Not Sure',ingredients:[] as any[],intended_use:'General wellness',claims:'',classical_formulation:'Unsure',developed_by_org:'Unsure',traditionally_known:'Unsure',biological_resource:'Unknown',commercial_use:'Unknown',ip_goals:[] as string[]};
export default function Assessment(){const [s,setS]=useState(0);const [a,setA]=useState<any>(base);const [r,setR]=useState<any>(null);const [loading,setLoading]=useState(false);const router=useRouter(); const set=(k:string,v:any)=>setA((x:any)=>({...x,[k]:v}));
useEffect(()=>{if(!r) return; sessionStorage.setItem('ipSaktiAssessment',JSON.stringify({input:a,result:r}));},[r]);
const submit=async()=>{setLoading(true);try{const x=await postJSON('/api/assessment',a);setR(x);setS(5)}finally{setLoading(false)}};
const addIng=(name:string)=>set('ingredients',[...a.ingredients,{name,scientific_name:'',source:'Plant',source_location:'India',traditional_use:'Unknown'}]);
if(s===5&&r)return <main className="container page"><div className="pageHead"><div><div className="eyebrow">IP-SAKTI Preliminary Innovation Health Check</div><h1>Your Ayurvedic Innovation Health Check</h1><p>From Product Idea to Protection Pathway.</p></div><button className="btn primary" onClick={()=>router.push('/ask')}>Ask AI About Your Assessment</button></div><div className="resultTop"><div className="card"><span className="badge">PRELIMINARY / NOT LEGAL ADVICE</span><h2 style={{marginTop:14}}>Likely classification: {r.classification.category}</h2><p className="muted">Confidence: <b>{r.classification.confidence}%</b></p><p>{r.classification.reasons.join(' • ')}</p><div className="notice">Important: This is a preliminary AI-assisted classification, not an official regulatory determination.</div></div><div className="scoreCard"><div>Overall Readiness</div><div className="bigScore">{r.health_score.overall}</div><div>/100</div></div></div><div className="indicatorGrid">{Object.entries(r.health_score.breakdown).map(([k,v]:any)=><div className="indicator" key={k}><b>{k}</b><div style={{fontSize:30,fontFamily:'Manrope',fontWeight:800,margin:'8px 0'}}>{v}</div><span className={'status '+r.flags[k.toLowerCase().replaceAll(' ','_')]}>PRELIMINARY</span></div>)}</div><div className="section"><h2>Top Issues</h2><div className="grid3">{r.top_issues.length?r.top_issues.map((x:string)=><div className="card" key={x}><b>Review required</b><p>{x}</p><button className="btn secondary">Why?</button></div>):<div className="card">No major issue identified from the current inputs.</div>}</div></div><div className="section"><h2>Recommended Next Steps</h2><div className="roadmap">{r.roadmap.map((x:any)=><div className="road" key={x.action}><span className="badge">{x.priority}</span><div><b>{x.action}</b><div className="muted">{x.reason}</div></div><span>→</span></div>)}</div></div><div className="section"><h2>Protection Pathway</h2><div className="grid3">{[['Patent',r.flags.prior_art],['Trademark',r.flags.trademark],['Design','GREY'],['Copyright','GREY'],['GI','GREY'],['Trade Secret','YELLOW']].map(([x,y]:any)=><div className="card" key={x}><b>{x}</b><div className={'status '+y} style={{marginTop:12}}>{y==='GREEN'?'POTENTIALLY RELEVANT':y==='YELLOW'?'REVIEW REQUIRED':'NOT PRIMARY IN THIS ASSESSMENT'}</div></div>)}</div></div><div className="notice">{r.disclaimer}</div></main>;
return <main className="container page"><div className="pageHead"><div><div className="eyebrow">Product Assessment</div><h1>Understand your product before you protect it.</h1><p>Keep the assessment short. You can refine details later.</p></div><span className="badge">Step {s+1} of 6</span></div><div className="wizard"><aside className="steps">{steps.map((x,i)=><div className={'step '+(i===s?'active':'')} key={x}>{i+1}. {x}</div>)}</aside><section className="card formCard">
{s===0&&<><h2>Product</h2><div className="field"><label>Product Name</label><input className="input" value={a.product_name} onChange={e=>set('product_name',e.target.value)} placeholder="e.g. Herbal Wellness Syrup"/></div><div className="field"><label>Product Description</label><textarea className="textarea" value={a.description} onChange={e=>set('description',e.target.value)} placeholder="What is the product and what makes it different?"/></div><Choice label="Product Type" value={a.product_type} options={['Ayurvedic Medicine','Herbal Food / Ayurveda Aahar','Cosmetic','Supplement','Other','Not Sure']} onChange={(v:any)=>set('product_type',v)}/></>}
{s===1&&<><h2>Ingredients</h2><p className="muted">Ingredient suggestions are demonstration helpers, not legal classifications.</p><div className="choices">{ingSuggestions.map(x=><button className="choice" key={x} onClick={()=>addIng(x)}>+ {x}</button>)}</div><div style={{marginTop:20}}>{a.ingredients.map((x:any,i:number)=><div className="card" style={{marginBottom:10}} key={i}><div className="row2"><div><label>Name</label><input className="input" value={x.name} onChange={e=>{const z=[...a.ingredients];z[i]={...x,name:e.target.value};set('ingredients',z)}}/></div><div><label>Source location</label><select className="select" value={x.source_location} onChange={e=>{const z=[...a.ingredients];z[i]={...x,source_location:e.target.value};set('ingredients',z)}}><option>India</option><option>Outside India</option><option>Unknown</option></select></div></div></div>)}</div></>}
{s===2&&<><h2>Intended Use</h2><Choice label="What is your product intended for?" value={a.intended_use} options={['General wellness','Therapeutic use','Food/nutrition','Cosmetic','Preventive use','Other']} onChange={(v:any)=>set('intended_use',v)}/><div className="field" style={{marginTop:22}}><label>What claims do you intend to make?</label><textarea className="textarea" value={a.claims} onChange={e=>set('claims',e.target.value)}/></div></>}
{s===3&&<><h2>Formulation</h2><Choice label="Based on an established/classical Ayurveda text?" value={a.classical_formulation} options={['Yes','No','Unsure']} onChange={(v:any)=>set('classical_formulation',v)}/><Choice label="Was this formulation developed by your organization?" value={a.developed_by_org} options={['Yes','No','Unsure']} onChange={(v:any)=>set('developed_by_org',v)}/><Choice label="May the formulation already be traditionally known?" value={a.traditionally_known} options={['Yes','No','Unsure']} onChange={(v:any)=>set('traditionally_known',v)}/></>}
{s===4&&<><h2>Business Goal</h2><p className="muted">Select all that apply.</p><div className="choices">{['Launch product','Protect invention','Protect brand','Search existing patents','Check traditional knowledge','Understand compliance','Assess ABS','Estimate IP cost'].map(x=><button className={'choice '+(a.ip_goals.includes(x.replace('Protect invention','Patent').replace('Protect brand','Trademark'))?'selected':'')} key={x} onClick={()=>{const v=x==='Protect invention'?'Patent':x==='Protect brand'?'Trademark':x;set('ip_goals',a.ip_goals.includes(v)?a.ip_goals.filter((y:string)=>y!==v):[...a.ip_goals,v])}}>{x}</button>)}</div><div className="row2" style={{marginTop:25}}><Choice label="Uses biological resources?" value={a.biological_resource} options={['Yes','No','Unknown']} onChange={(v:any)=>set('biological_resource',v)}/><Choice label="Commercial use?" value={a.commercial_use} options={['Yes','No','Unknown']} onChange={(v:any)=>set('commercial_use',v)}/></div></>}
{s<5&&<div className="actions"><button className="btn secondary" disabled={s===0} onClick={()=>setS(s-1)}>Back</button>{s<4?<button className="btn primary" onClick={()=>setS(s+1)}>Continue</button>:<button className="btn primary" onClick={submit}>{loading?'Analyzing…':'Generate Assessment'}</button>}</div>}
</section></div></main>}
function Choice({label,value,options,onChange}:{label:string,value:string,options:string[],onChange:(v:string)=>void}){return <div className="field"><label>{label}</label><div className="choices">{options.map(x=><button type="button" className={'choice '+(value===x?'selected':'')} onClick={()=>onChange(x)} key={x}>{x}</button>)}</div></div>}
