import json

patents = [
  {
    "record_id": "416499",
    "title": "Smart Wearable device and method for estimating traditional medicine system parameters",
    "publication_number": "416499",
    "applicant": "AYUR.AI (OPC) PRIVATE LIMITED",
    "inventor": "BALA PESALA",
    "filing_date": "Unknown",
    "publication_date": "2023-01-02",
    "status": "Granted",
    "ingredients": ["Wearable sensor parameters"],
    "purpose": "Estimating traditional medicine parameters",
    "technical_features": "Smart Wearable device and method",
    "classification": "A61B",
    "source_type": "official_grant",
    "official_record": True
  },
  {
    "record_id": "429737",
    "title": "Integrative system and method for performing medical Diagnosis using Artificial Intelligence",
    "publication_number": "429737",
    "applicant": "Ayur.AI (OPC) Private Limited",
    "inventor": "Balasubrahmanyam Pesala",
    "filing_date": "Unknown",
    "publication_date": "2023-04-24",
    "status": "Granted",
    "ingredients": ["AI", "Diagnosis data"],
    "purpose": "Medical diagnosis",
    "technical_features": "Artificial Intelligence system",
    "classification": "G16H",
    "source_type": "official_grant",
    "official_record": True
  },
  {
    "record_id": "379565",
    "title": "Herbal cigarette and process of preparation thereof",
    "publication_number": "379565",
    "applicant": "RAJAS UDAY NITSURE, UDAY ANANT NITSURE",
    "inventor": "Rajas Uday Nitsure, Uday Anant Nitsure",
    "filing_date": "Unknown",
    "publication_date": "2021-10-21",
    "status": "Granted",
    "ingredients": ["Herbal ingredients"],
    "purpose": "Smoking alternative",
    "technical_features": "Herbal cigarette preparation",
    "classification": "A24B",
    "source_type": "official_grant",
    "official_record": True
  },
  {
    "record_id": "377408",
    "title": "Vaginal douche composition based on herbal extracts",
    "publication_number": "377408",
    "applicant": "VEE EXCEL DRUGS & PHARMACEUTICALS PVT. LTD.",
    "inventor": "Bansal Vipin, Kushwaha Ashok Kumar",
    "filing_date": "Unknown",
    "publication_date": "2021-09-21",
    "status": "Granted",
    "ingredients": ["Herbal extracts"],
    "purpose": "Hygiene/Medical",
    "technical_features": "Vaginal douche composition",
    "classification": "A61K",
    "source_type": "official_grant",
    "official_record": True
  },
  {
    "record_id": "421133",
    "title": "Herbal incense formulation",
    "publication_number": "421133",
    "applicant": "GLOBAL CONSUMER PRODUCTS LIMITED",
    "inventor": "Ashish Bhobe, Sridhar Srinivasan, Pavana Nair, Jitendra Pandyaji",
    "filing_date": "Unknown",
    "publication_date": "2023-02-10",
    "status": "Granted",
    "ingredients": ["Herbal ingredients"],
    "purpose": "Incense",
    "technical_features": "Incense formulation",
    "classification": "A61L",
    "source_type": "official_grant",
    "official_record": True
  },
  {
    "record_id": "436895",
    "title": "Herbal sanitary pad",
    "publication_number": "436895",
    "applicant": "Poonam Bhatt",
    "inventor": "Poonam Bhatt, Krishi Bhatt",
    "filing_date": "Unknown",
    "publication_date": "2023-07-03",
    "status": "Granted",
    "ingredients": ["Herbal components"],
    "purpose": "Sanitary hygiene",
    "technical_features": "Herbal sanitary pad",
    "classification": "A61F",
    "source_type": "official_grant",
    "official_record": True
  },
  {
    "record_id": "319506",
    "title": "Herbal soap",
    "publication_number": "319506",
    "applicant": "Khumujam Jina",
    "inventor": "Khumujam Jina",
    "filing_date": "Unknown",
    "publication_date": "2019-08-30",
    "status": "Granted",
    "ingredients": ["Herbal extract"],
    "purpose": "Cleaning/Hygiene",
    "technical_features": "Herbal soap composition",
    "classification": "C11D",
    "source_type": "official_grant",
    "official_record": True
  },
  {
    "record_id": "282906",
    "title": "A novel antimicrobial polyherbal composition",
    "publication_number": "282906",
    "applicant": "The Talwar Research Foundation",
    "inventor": "Gursaran Talwar, Mahendra Rai, Kavita Bansal",
    "filing_date": "Unknown",
    "publication_date": "2017-05-05",
    "status": "Granted",
    "ingredients": ["Polyherbal extracts"],
    "purpose": "Antimicrobial",
    "technical_features": "Antimicrobial composition",
    "classification": "A61K",
    "source_type": "official_grant",
    "official_record": True
  },
  {
    "record_id": "426371",
    "title": "Synergistic herbal hair growth formulation for alopecia",
    "publication_number": "426371",
    "applicant": "H.N.B. GARHWAL UNIVERSITY",
    "inventor": "Mona Semalty, Ajay Semalty, Tej Sevak, Yuveraj Tanwar, Mohan Rawat",
    "filing_date": "Unknown",
    "publication_date": "2023-03-22",
    "status": "Granted",
    "ingredients": ["Synergistic herbs"],
    "purpose": "Hair growth/alopecia",
    "technical_features": "Synergistic formulation",
    "classification": "A61K",
    "source_type": "official_grant",
    "official_record": True
  },
  {
    "record_id": "AYUSH-64",
    "title": "Poly-herbal anti-malarial drug AYUSH-64",
    "publication_number": "AYUSH-64",
    "applicant": "CCRAS through NRDC",
    "inventor": "CCRAS",
    "filing_date": "1980",
    "publication_date": "1980",
    "status": "Granted",
    "ingredients": ["35 phytoconstituents"],
    "purpose": "Anti-malarial, Repurposed for COVID-19",
    "technical_features": "Poly-herbal formulation",
    "classification": "A61K",
    "source_type": "official_grant",
    "official_record": True
  }
]

with open("backend/data/patents.json", "w", encoding="utf-8") as f:
    json.dump(patents, f, indent=2)

print("patents.json updated.")
